//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmRuleCatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlarmRuleCatalog()
        {
            this.AlarmNotification = new HashSet<AlarmNotification>();
            this.AlarmRuleItem = new HashSet<AlarmRuleItem>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int MessageCatalogId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int KeepHappenInSec { get; set; }
        public bool ActiveFlag { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public bool DeletedFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmNotification> AlarmNotification { get; set; }
        public virtual Company Company { get; set; }
        public virtual MessageCatalog MessageCatalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmRuleItem> AlarmRuleItem { get; set; }
    }
}
