//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmNotification
    {
        public int Id { get; set; }
        public Nullable<int> AlarmRuleCatalogId { get; set; }
        public Nullable<int> ExternalApplicationId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public bool DeletedFlag { get; set; }
    
        public virtual AlarmRuleCatalog AlarmRuleCatalog { get; set; }
        public virtual ExternalApplication ExternalApplication { get; set; }
    }
}
