//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalApplication()
        {
            this.AlarmNotification = new HashSet<AlarmNotification>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string MessageTemplate { get; set; }
        public string TargetType { get; set; }
        public string Method { get; set; }
        public string ServiceURL { get; set; }
        public string AuthType { get; set; }
        public string AuthID { get; set; }
        public string AuthPW { get; set; }
        public string TokenURL { get; set; }
        public string HeaderValues { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public bool DeletedFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmNotification> AlarmNotification { get; set; }
        public virtual Company Company { get; set; }
    }
}
