//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class IoTHub
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IoTHub()
        {
            this.IoTDevice = new HashSet<IoTDevice>();
        }
    
        public string IoTHubAlias { get; set; }
        public string Description { get; set; }
        public int CompanyID { get; set; }
        public string P_IoTHubEndPoint { get; set; }
        public string P_IoTHubConnectionString { get; set; }
        public string P_EventConsumerGroup { get; set; }
        public string P_EventHubStorageConnectionString { get; set; }
        public string P_UploadContainer { get; set; }
        public string S_IoTHubEndPoint { get; set; }
        public string S_IoTHubConnectionString { get; set; }
        public string S_EventConsumerGroup { get; set; }
        public string S_EventHubStorageConnectionString { get; set; }
        public string S_UploadContainer { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public bool DeletedFlag { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IoTDevice> IoTDevice { get; set; }
    }
}
