//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MessageElement()
        {
            this.AlarmRuleItem = new HashSet<AlarmRuleItem>();
            this.AlarmRuleItem1 = new HashSet<AlarmRuleItem>();
        }
    
        public int Id { get; set; }
        public int MessageCatalogID { get; set; }
        public string ElementName { get; set; }
        public string ElementDataType { get; set; }
        public Nullable<int> ChildMessageCatalogID { get; set; }
        public bool MandatoryFlag { get; set; }
        public bool SFMandatoryFlag { get; set; }
        public Nullable<bool> ShowOnEquipmentList { get; set; }
        public Nullable<bool> ShowOnFactoryBoard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmRuleItem> AlarmRuleItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmRuleItem> AlarmRuleItem1 { get; set; }
        public virtual MessageCatalog MessageCatalog { get; set; }
    }
}
