//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsageLogSumByDay
    {
        public long Id { get; set; }
        public Nullable<int> CompanyQty { get; set; }
        public Nullable<int> FactoryQty { get; set; }
        public Nullable<int> EquipmentQty { get; set; }
        public Nullable<long> DeviceMessage { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    }
}
