SET IDENTITY_INSERT [SmartFactory].[SuperAdmin] ON
INSERT INTO [SmartFactory].[SuperAdmin] ([Id], [FirstName], [LastName], [Email], [Password]) VALUES (1, N'Super', N'Admin', N'super@cdstudio.com', N'AFns/VMam+LzA9lb9bvrSlFyLSJf1fP/C/sU7hoHDCTMaaQLKEfX9yb7V3qyXLWtEg==')
SET IDENTITY_INSERT [SmartFactory].[SuperAdmin] OFF


SET IDENTITY_INSERT [SmartFactory].[DeviceType] ON
INSERT INTO [SmartFactory].[DeviceType] ([Id], [Name], [Description]) VALUES (1, N'Device', NULL)
INSERT INTO [SmartFactory].[DeviceType] ([Id], [Name], [Description]) VALUES (2, N'Gateway', NULL)
SET IDENTITY_INSERT [SmartFactory].[DeviceType] OFF


INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'aa', N'Afar')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ab', N'Abkhazian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'af-ZA', N'Afrikaans')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'am', N'Amharic')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar', N'Arabic')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-AE', N'Arabic (Uae)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-BH', N'Arabic (Bahrain)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-DZ', N'Arabic (Algeria)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-EG', N'Arabic (Egypt)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-IQ', N'Arabic (Iraq)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-JO', N'Arabic (Jordan)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-KW', N'Arabic (Kuwait)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-LB', N'Arabic (Lebanon)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-LY', N'Arabic (Libya)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-MA', N'Arabic (Morocco)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-OM', N'Arabic (Oman)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-QA', N'Arabic (Qatar)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-SA', N'Arabic (Saudi Arabia)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-SD', N'Arabic (Sudan)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-SY', N'Arabic (Syria)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-TN', N'Arabic (Tunisia)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-YE', N'Arabic (Yemen)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'as', N'Assamese')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ay', N'Aymara')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'az', N'Azeri')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ba', N'Bashkir')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'be-BY', N'Belarusian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'bg-BG', N'Bulgarian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'bh', N'Bihari')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'bi', N'Bislama')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'bn', N'Bengali')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'bo', N'Tibetan')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'br', N'Breton')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ca-ES', N'Catalan')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'co', N'Corsican')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'cs-CZ', N'Czech')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'cy', N'Welsh')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'da-DK', N'Danish')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'de-AT', N'German (Austrian)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'de-BE', N'German (Belgium)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'de-CH', N'German (Swiss)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'de-DE', N'German')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'de-LI', N'German (Liechtenstein)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'de-LU', N'German (Luxembourg)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'dz', N'Bhutani')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'el-GR', N'Greek')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-AU', N'English (Australia)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-BW', N'English (Botswana)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-BZ', N'English (Belize)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-CA', N'English (Canada)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-CB', N'English (Caribbean)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-DK', N'English (Denmark)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-GB', N'English')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-IE', N'English (Eire)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-JM', N'English (Jamaica)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-NZ', N'English (New Zealand)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-PH', N'English (Philippines)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-TT', N'English (Trinidad)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-US', N'English (U.S.)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-ZA', N'English (South Africa)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-ZW', N'English (Zimbabwe)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'eo', N'Esperanto')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-AR', N'Spanish (Argentina)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-BO', N'Spanish (Bolivia)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-CL', N'Spanish (Chile)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-CO', N'Spanish (Colombia)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-CR', N'Spanish (Costa Rica)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-DO', N'Spanish (Dominican republic)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-EC', N'Spanish (Ecuador)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-ES', N'Spanish')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-GT', N'Spanish (Guatemala)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-HN', N'Spanish (Honduras)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-MX', N'Spanish (Mexican)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-NI', N'Spanish (Nicaragua)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-PA', N'Spanish (Panama)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-PE', N'Spanish (Peru)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-PR', N'Spanish (Puerto Rico)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-PY', N'Spanish (Paraguay)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-SV', N'Spanish (El Salvador)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-US', N'Spanish (U.S.)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-UY', N'Spanish (Uruguay)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-VE', N'Spanish (Venezuela)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'et-EE', N'Estonian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'eu-ES', N'Basque')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fa-IR', N'Farsi')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fi-FI', N'Finnish')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fj', N'Fiji')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fo-FO', N'Faeroese')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fr-BE', N'French (Belgian)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fr-CA', N'French (Canadian)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fr-CH', N'French (Swiss)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fr-FR', N'French')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fr-LU', N'French (Luxembourg)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fr-MC', N'French (Monaco)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fy', N'Frisian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ga-IE', N'Irish')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'gd', N'Scots Gaelic')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'gl-ES', N'Galician')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'gn', N'Guarani')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'gu', N'Gujarati')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ha', N'Hausa')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'he-IL', N'Hebrew')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'hi-IN', N'Hindi')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'hr-HR', N'Croatian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'hu-HU', N'Hungarian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'hy', N'Armenian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ia', N'Interlingua')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'id-ID', N'Indonesian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ie', N'Interlingue')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ik', N'Inupiak')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'is-IS', N'Icelandic')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'it-CH', N'Italian (Swiss)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'it-IT', N'Italian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'iu', N'Inuktitut')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ja-JP', N'Japanese')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'jw', N'Javanese')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ka-GE', N'Georgian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'kk', N'Kazakh')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'kl-GL', N'Greenlandic')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'km', N'Cambodian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'kn', N'Kannada')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ko-KR', N'Korean')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ks', N'Kashmiri')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ks-IN', N'Kashmiri (India)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ku-TR', N'Kurdish')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'kw-GB', N'Kernewek')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ky', N'Kirghiz')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'la', N'Latin')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ln', N'Lingala')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'lo', N'Laothian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'lt-LT', N'Lithuanian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'lv-LV', N'Latvian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'mg', N'Malagasy')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'mi', N'Maori')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'mk-MK', N'Macedonian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ml', N'Malayalam')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'mn', N'Mongolian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'mo', N'Moldavian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'mr-IN', N'Marathi')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ms-BN', N'Malay (Brunei Darussalam)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ms-MY', N'Malay')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'mt-MT', N'Maltese')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'my', N'Burmese')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'na', N'Nauru')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'nb-NO', N'Norwegian (Bokmal)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ne-IN', N'Nepali (India)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ne-NP', N'Nepali')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'nl-BE', N'Dutch (Belgian)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'nl-NL', N'Dutch')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'nn-NO', N'Norwegian (Nynorsk)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'oc', N'Occitan')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'om', N'(Afan) Oromo')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'or', N'Oriya')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'pa', N'Punjabi')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'pl-PL', N'Polish')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ps', N'Pashto, Pushto')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'pt-BR', N'Portuguese (Brazilian)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'pt-PT', N'Portuguese')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'qu', N'Quechua')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'rm', N'Rhaeto-Romance')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'rn', N'Kirundi')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ro-RO', N'Romanian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ru-RU', N'Russian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ru-UA', N'Russian (Ukraine)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'rw', N'Kinyarwanda')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sa', N'Sanskrit')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sd', N'Sindhi')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'se-NO', N'Northern Sami')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sg', N'Sangho')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sh', N'Serbo-Croatian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'si', N'Sinhalese')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sk-SK', N'Slovak')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sl-SI', N'Slovenian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sm', N'Samoan')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sn', N'Shona')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'so', N'Somali')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sq-AL', N'Albanian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sr-SR', N'Serbian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sr-SR@lati', N'Serbian (Latin)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ss', N'Siswati')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'st', N'Sesotho')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'su', N'Sundanese')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sv-FI', N'Swedish (Finland)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sv-SE', N'Swedish')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sw-KE', N'Swahili')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ta', N'Tamil')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'te', N'Telugu')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'tg', N'Tajik')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'th-TH', N'Thai')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ti', N'Tigrinya')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'tk', N'Turkmen')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'tl-PH', N'Tagalog')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'tn', N'Setswana')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'to', N'Tonga')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'tr-TR', N'Turkish')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ts', N'Tsonga')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'tt', N'Tatar')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'tw', N'Twi')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ug', N'Uighur')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'uk-UA', N'Ukrainian')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ur', N'Urdu')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ur-IN', N'Urdu (India)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ur-PK', N'Urdu (Pakistan)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'uz', N'Uzbek')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'vi-VN', N'Vietnamese')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'vo', N'Volapuk')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'wo', N'Wolof')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'xh', N'Xhosa')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'yi', N'Yiddish')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'yo', N'Yoruba')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'za', N'Zhuang')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'zh-CN', N'Chinese (Simplified)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'zh-HK', N'Chinese (Hongkong)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'zh-MO', N'Chinese (Macau)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'zh-SG', N'Chinese (Singapore)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'zh-TW', N'Chinese (Taiwan)')
INSERT INTO [SmartFactory].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'zu', N'Zulu')


SET IDENTITY_INSERT [SmartFactory].[MessageMandatoryElementDef] ON
INSERT INTO [SmartFactory].[MessageMandatoryElementDef] ([Id], [ElementName], [ElementDataType], [MandatoryFlag], [Description]) VALUES (1, N'companyId', N'numeric', 1, NULL)
INSERT INTO [SmartFactory].[MessageMandatoryElementDef] ([Id], [ElementName], [ElementDataType], [MandatoryFlag], [Description]) VALUES (2, N'msgTimestamp', N'datetime', 1, N'2016-12-01 08:00:00 (local time)')
INSERT INTO [SmartFactory].[MessageMandatoryElementDef] ([Id], [ElementName], [ElementDataType], [MandatoryFlag], [Description]) VALUES (3, N'equipmentId', N'string', 1, NULL)
INSERT INTO [SmartFactory].[MessageMandatoryElementDef] ([Id], [ElementName], [ElementDataType], [MandatoryFlag], [Description]) VALUES (4, N'equipmentRunStatus', N'numeric', 1, N'-1: stop | 0: idle | 1: run')
SET IDENTITY_INSERT [SmartFactory].[MessageMandatoryElementDef] OFF


SET IDENTITY_INSERT [SmartFactory].[PermissionCatalog] ON
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (1, N'Factory View', NULL, 10, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (2, N'Factory Edit', NULL, 11, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (3, N'Equipment View', NULL, 20, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (4, N'Equipment Edit', NULL, 21, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (5, N'IoT Device View', NULL, 30, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (6, N'IoT Device Edit', NULL, 31, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (7, N'IoT Device Configuration Management View', NULL, 32, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (8, N'IoT Device Configuration Management Edit', NULL, 33, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (9, N'IoT Device Message Attach View', NULL, 34, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (10, N'IoT Device Message Attach Edit', NULL, 35, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (11, N'Message View', NULL, 40, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (12, N'Message Edit', NULL, 41, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (13, N'Message Element View', NULL, 42, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (14, N'Message Element Edit', NULL, 43, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (15, N'Monitor Running Task', NULL, 50, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (16, N'Monitor IoT Hubs', NULL, 51, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (17, N'Monitor Usage Log', NULL, 52, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (18, N'Setup Alarm Rule Catalog', NULL, 100, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (19, N'Setup Alarm Notify', NULL, 101, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (20, N'Setup Device Certificate', NULL, 102, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (21, N'Setup IoT Hub Alias', NULL, 103, N'2017-01-06 01:27:21', NULL, 1)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (22, N'Setup Employee', NULL, 104, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (23, N'Setup Role', NULL, 105, N'2017-01-06 01:27:21', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (24, N'Setup Dashboard', NULL, 106, N'2017-02-08 08:14:22', NULL, 1)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (25, N'Setup External Application', NULL, 107, N'2017-02-08 08:14:41', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (26, N'Setup Widget Catalog', NULL, 108, N'2017-02-08 08:15:24', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (27, N'Dashboard Company View', N'View permission of Company of Dashboard', 60, N'2017-02-08 08:15:24', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (28, N'Dashboard Factory View', N'View permission of Factory of Dashboard', 61, N'2017-02-08 08:15:24', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (29, N'Dashboard Equipment View', N'View permission of Equipment of Dashboard', 62, N'2017-02-08 08:15:24', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (30, N'Setup Customize Device Configuration', N'Setup Customize Device Configuration', 109, N'2017-02-08 08:15:24', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (31, N'Dashboard Company Edit', N'Edit permission for Company of Dashboard', 63, N'2017-02-08 08:15:24', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (32, N'Dashboard Factory Edit', N'Edit permission for Factory of Dashboard', 64, N'2017-02-08 08:15:24', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (33, N'Dashboard Equipment Edit', N'Edit permission of Equipment Dashboard', 65, N'2017-02-08 08:15:24', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (34, N'Setup Equipment Class', N'Setup Equipment Class', 110, N'2017-02-08 08:15:24', NULL, 0)
INSERT INTO [SmartFactory].[PermissionCatalog] ([Id], [Name], [Description], [PermissionId], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (35, N'Setup Equipment Meta-Data', N'Setup Equipment Meta-Data', 111, N'2017-02-08 08:15:24', NULL, 0)
SET IDENTITY_INSERT [SmartFactory].[PermissionCatalog] OFF

SET IDENTITY_INSERT [SmartFactory].[IoTDeviceConfiguration] ON
INSERT INTO [SmartFactory].[IoTDeviceConfiguration] ([Id], [Name], [DataType], [Description], [DefaultValue]) VALUES (1, N'MinSmartFactorySDKVersion', N'string', N'Min SmartFactory SDK Version', N'1.2')
INSERT INTO [SmartFactory].[IoTDeviceConfiguration] ([Id], [Name], [DataType], [Description], [DefaultValue]) VALUES (2, N'DataCompression', N'bool', N'Enforce Data Compression', N'false')
INSERT INTO [SmartFactory].[IoTDeviceConfiguration] ([Id], [Name], [DataType], [Description], [DefaultValue]) VALUES (3, N'UploadLogData', N'bool', N'Upload Device Log Data to Backend', N'true')
SET IDENTITY_INSERT [SmartFactory].[IoTDeviceConfiguration] OFF

SET IDENTITY_INSERT [SmartFactory].[WidgetClass] ON
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (18, N'Alarm Card', 100, N'company', N'/assets/images/widget/AlarmCard.PNG', 3, 120, N'2017-03-01 13:25:27', N'2017-08-12 12:50:30', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (21, N'Alarm List', 101, N'company', N'/assets/images/widget/AlarmList.PNG', 6, 120, N'2017-03-01 13:26:31', N'2017-08-12 12:50:49', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (16, N'Equipment Card', 102, N'company', N'/assets/images/widget/EquipmentCard.PNG', 0, 0, N'2017-03-01 13:24:50', N'2017-08-12 14:38:37', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (14, N'Factory Card', 103, N'company', N'/assets/images/widget/FactoryCard.PNG', 0, 0, N'2017-03-01 07:12:48', N'2017-08-12 14:38:57', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (20, N'Factory List', 104, N'company', N'/assets/images/widget/FactoryList.PNG', 0, 0, N'2017-03-01 13:26:15', N'2017-08-12 14:39:13', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (19, N'Google Map Card', 105, N'company', N'/assets/images/widget/GoogleMapCard.PNG', 3, 120, N'2017-03-01 13:26:04', N'2017-08-12 12:51:17', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (13, N'Logo Card', 106, N'company', N'/assets/images/widget/CompanyLogoCard.PNG', 0, 0, N'2017-03-01 07:12:34', N'2017-08-12 14:39:45', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (37, N'HTML Content Card', 107, N'company', N'/assets/images/widget/HTMLContent.PNG', 0, 0, N'2017-08-12 12:49:41', N'2017-08-12 12:56:40', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (40, N'Preferred OEE', 108, N'company', N'/assets/images/widget/PreferredOEE.PNG', 0, 0, N'2017-11-01 10:57:05', N'2017-11-01 10:57:22', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (25, N'Alarm Card', 200, N'factory', N'/assets/images/widget/AlarmCard.PNG', 0, 0, N'2017-03-01 15:28:07', N'2017-08-12 14:40:16', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (26, N'Alarm List', 201, N'factory', N'/assets/images/widget/AlarmList.PNG', 0, 0, N'2017-03-01 15:28:19', N'2017-08-12 14:40:28', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (22, N'Company Logo Card', 202, N'factory', N'/assets/images/widget/CompanyLogoCard.PNG', 0, 0, N'2017-03-01 15:27:33', N'2017-08-12 14:40:42', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (24, N'Equipment Card', 203, N'factory', N'/assets/images/widget/EquipmentCard.PNG', 0, 0, N'2017-03-01 15:27:59', N'2017-08-12 14:40:56', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (27, N'Equipment List', 204, N'factory', N'/assets/images/widget/EquipmentList.PNG', 0, 0, N'2017-03-01 15:28:32', N'2017-08-12 14:41:10', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (28, N'Google Map Card', 205, N'factory', N'/assets/images/widget/GoogleMapCard.PNG', 0, 0, N'2017-03-01 15:28:40', N'2017-08-12 14:41:24', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (23, N'Factory Photo Card', 206, N'factory', N'/assets/images/widget/FactoryPhotoCard.PNG', 0, 0, N'2017-03-01 15:27:47', N'2017-08-12 14:41:41', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (29, N'Video Card', 207, N'factory', N'/assets/images/widget/VideoCard.PNG', 0, 0, N'2017-03-01 15:28:55', N'2017-08-12 14:41:59', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (38, N'HTML Content Card', 208, N'factory', N'/assets/images/widget/HTMLContent.PNG', 0, 0, N'2017-08-12 13:03:53', N'2017-08-12 14:42:17', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (39, N'Preferred OEE', 209, N'factory', N'/assets/images/widget/PreferredOEE.PNG', 0, 0, N'2017-11-01 10:56:51', N'2017-11-01 10:57:32', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (42, N'Google Map Equipment List Circle', 210, N'factory', N'/assets/images/widget/GoogleMapEquipmentListCircle.PNG', 0, 0, N'2018-02-12 14:28:59', N'2018-02-12 14:33:13', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (12, N'Alarm Card', 300, N'equipment', N'/assets/images/widget/AlarmCard.PNG', 3, 5, N'2017-02-23 12:12:55', N'2017-02-23 15:05:52', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (1, N'Bar Chart', 301, N'equipment', N'/assets/images/widget/BarChart.PNG', 4, 6, N'2017-01-21 09:32:16', N'2017-02-21 07:33:21', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (2, N'Basic Card', 302, N'equipment', N'/assets/images/widget/BasicCard.PNG', 4, 8, N'2017-01-21 09:33:11', N'2017-05-20 11:14:37', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (10, N'Google Map Card', 303, N'equipment', N'/assets/images/widget/GoogleMapCard.PNG', 4, 6, N'2017-02-18 04:29:47', N'2017-03-11 08:13:57', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (9, N'Image Card', 304, N'equipment', N'my URL', 4, 6, N'2017-01-25 03:20:47', N'2017-01-30 03:18:58', 1)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (3, N'Line Chart', 305, N'equipment', N'/assets/images/widget/LineChart.PNG', 3, 6, N'2017-01-21 09:32:11', N'2017-02-23 15:00:59', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (4, N'Percentage Card', 306, N'equipment', N'/assets/images/widget/PercentageCard.PNG', 3, 5, N'2017-01-21 09:32:56', N'2017-01-30 15:19:26', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (5, N'Pie Chart', 307, N'equipment', N'/assets/images/widget/PieChart.png', 3, 6, N'2017-01-21 09:32:20', N'2017-01-25 09:58:35', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (6, N'Text Card', 308, N'equipment', N'/assets/images/widget/TextCard.PNG', 3, 5, N'2017-01-21 09:32:59', N'2017-01-30 07:25:21', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (11, N'Text List Card', 309, N'equipment', N'/assets/images/widget/TextListCard.PNG', 4, 6, N'2017-02-18 12:39:30', N'2017-02-18 12:40:19', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (31, N'Alarm List', 310, N'equipment', N'/assets/images/widget/AlarmList.PNG', 6, 15, N'2017-03-21 08:12:49', N'2017-05-19 03:02:54', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (32, N'Google Map Location Trace', 311, N'equipment', N'/assets/images/widget/GoogleMapLocationTrace.PNG', 4, 6, N'2017-05-03 02:50:34', N'2017-05-03 02:52:29', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (33, N'Simple OEE Card', 312, N'equipment', N'/assets/images/widget/SimpleOEE.PNG', 4, 7, N'2017-05-16 15:36:34', N'2017-05-19 03:22:40', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (34, N'Preferred OEE Card', 313, N'equipment', N'/assets/images/widget/PreferredOEE.PNG', 6, 7, N'2017-05-16 15:37:26', N'2017-05-19 03:22:28', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (35, N'HTML Content Card', 314, N'equipment', N'/assets/images/widget/HTMLContent.PNG', 3, 120, N'2017-08-10 14:56:42', N'2017-08-12 12:20:22', 0)
INSERT INTO [SmartFactory].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [MinWidth], [MinHeight], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (36, N'Google Map Equipment Circle', 315, N'equipment', N'/assets/images/widget/GoogleMapEquipmentCircle.PNG', 0, 0, N'2017-08-10 14:57:24', N'2018-02-12 14:33:02', 0)
SET IDENTITY_INSERT [SmartFactory].[WidgetClass] OFF


